config/routes.rb
Budeals::Application.routes.draw do
  get "static_pages/home"

  get "static_pages/help"

  get "static_pages/faq"

  get "static_pages/login"

  get "static_pages/index"

  get "deals/cdeals"

  get "students/login"

   resources :students
   root :to => 'static_pages#home'
	
   resources :deals

end

app/models/deal.rb
class Deal < ActiveRecord::Base
  attr_accessible :category, :contactemail, :contactname, :contactnumber, :description, :name, :price
end

app/models/student.rb
class Student < ActiveRecord::Base
  attr_accessible :emailid, :firstname, :lastname, :password, :phoneno
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/deals_controller.rb
class DealsController < ApplicationController

def index
  @deals = Deal.all
end

  def show
    id = params[:id] # retrieve deal ID from URI route
    @deal = Deal.find(id) # Look up deal by unique ID
    # will render app/views/deals/show.<extension> by default
  end

  def new
	@deal = Deal.new
  end

 def create
   @deal = Deal.create!(params[:deal])
   if @deal.save
   	flash[:notice]="#{@deal.name} was successfully created"
   	redirect_to deals_path
   end 
 end

  def edit
    @deal = Deal.find params[:id]
  end

  def update
    @deal = Deal.find params[:id]
    @deal.update_attributes!(params[:deal])
    flash[:notice] = "#{@deal.name} was successfully updated."
    redirect_to deal_path(@deal)
  end

  def destroy
    @deal = Deal.find(params[:id])
    @deal.destroy
    flash[:notice] = "Deal '#{@deal.name}' deleted."
    redirect_to deals_path
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	def home
	end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController

 def new
   @student= Student.new
   @students = Student.find(:all)
 end


 def ddeals
   @student= Student.ddeals
   @students = Student.find(:all)
 end

 def ddetails
   @student= Student.ddetails
   @students = Student.find(:all)
 end

 def create
   @student = Student.new(params[:student])
   flash[:notice] = "User registered successfully"
   if @student.save
     redirect_to root_path
   end 
 end

 def login
	@student= Student.new
	@students = Student.find(:all)
 end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/deals_controller_helper.rb
module DealsControllerHelper
end

app/helpers/deals_helper.rb
module DealsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/deals/cdeals.html.erb
<body bgcolor="339966">
<hr>
<%= form_for @deal do |f| 

    %select{ :name => "Category[category_status]" }
    %option{:value => 1} = "Housing"
    %option{:value => 2} = "Books"
    %option{:value => 3} = "Electronics"
    %option{:value => 4} = "Others"

    Name: <%= f.text_field :name %><br />
    Description: <%= f.text_field :description %><br />
    Price: <%= f.text_field :price %><br />
    Contact Name: <%= f.text_field :contactname %><br />
    Contact Email: <%= f.text_field :contactemail %><br />
    Contact Number: <%= f.text_field :contactphonenumber %><br />
%p
    <%= f.submit %>
<% end -%>

<hr>
Display all the students information 
<% if !@deals.blank? %>
  <% for item in @deals %>
     <%= item.name %> <%= item.description %> <%= item.price %> <br/>
   <% end %>
<% else %>

<% end %>
<form action="http://localhost:3000/static_pages/home" method="link">
<p style="text-align: left;"><input type="submit" value="BACK TO HOME" />&nbsp;</p>
</form>
</body>

app/views/deals/edit.html.erb
<body bgcolor="339966">
<h1>Edit Deal</h1>
<%= form_for @deal do |f| -%>
  <div class="field">
    <%= f.label :category %><br />
    <%= f.select :category, options_for_select(%w[Books Electronics Housing Others]) %>
  </div>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>

  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>

  <div class="field">
    <%= f.label :contactname %><br />
    <%= f.text_field :contactname %>
  </div>

  <div class="field">
    <%= f.label :contactemail %><br />
    <%= f.text_field :contactemail %>
  </div>

  <div class="field">
    <%= f.label :contactnumber %><br />
    <%= f.text_field :contactnumber %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Back', deals_path %>

app/views/deals/index.html.erb
<body bgcolor="339966">
<h1>BUDeal$</h1>
<table>
<tr>
<th>Category</th>
<th>Name</th>
<th>Price</th>
<th>Details</th>
<th></th>
<th></th>
</tr>


<% @deals.each do |deal| %>
<tr>
<td><%= deal.category %></td>
<td><%= deal.name %></td>
<td><%= deal.price %></td>
<td><%= link_to 'Show', deal %></td>
<td><%= link_to 'Edit', edit_deal_path(deal) %></td>
<td><%= link_to 'Remove', deal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>
<% end %>
</table>
<br />
<%= link_to 'Create Deal', new_deal_path %> 

app/views/deals/new.html.erb
<body bgcolor="339966">
<h1>Create New Deal</h1>

<%= form_for @deal do |f| -%>
  <div class="field">
    <%= f.label :category %><br />
    <%= f.select :category, options_for_select(%w[Books Electronics Housing Others]) %>
  </div>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>

  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>

  <div class="field">
    <%= f.label :contactname %><br />
    <%= f.text_field :contactname %>
  </div>

  <div class="field">
    <%= f.label :contactemail %><br />
    <%= f.text_field :contactemail %>
  </div>
 
  <div class="field">
    <%= f.label :contactnumber %><br />
    <%= f.text_field :contactnumber %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>


<%= link_to 'Back', deals_path %>

app/views/deals/show.html.erb
<body bgcolor="339966">
<p>
  <b>Category:</b>
  <%= @deal.category %>
</p>

<p>
  <b>Name:</b>
  <%= @deal.name %>
</p>

<p>
  <b>Description:</b>
  <%= @deal.description %>
</p>

<p>
  <b>Contact Name:</b>
  <%= @deal.contactname %>
</p>

<p>
  <b>Contact Email:</b>
  <%= @deal.contactemail %>
</p>

<p>
  <b>Contact Phone Number:</b>
  <%= @deal.contactnumber %>
</p>



<%= link_to 'Edit Info', edit_deal_path(@deal) %> |
<%= button_to 'Delete', deal_path(@deal), :method => :delete, :confirm => 'Are you sure?' %>
<%= link_to 'Back to Display Deals', deals_path %> |

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Budeals</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title BUDeal$!
    = stylesheet_link_tag 'application'
    = javascript_include_tag 'application'
    = csrf_meta_tags

  %body
    %h1.title BUDeal$
    #main
      - if flash[:notice]
        #notice.message= flash[:notice]
      - elsif flash[:warning]
        #warning.message= flash[:warning]

      = yield

app/views/static_pages/cdeals.html.erb
<!DOCTYPE html>
<!-- Begin Form for Create Deal$-->
    
    <table cellspacing="5" cellpadding="5" border="0">
<html>
<head>
<title>Page Title</title>
</head>
<body>
<style>
body {
    background-color: #339966;
}

</style>
<h1>BUDeal$</h1>
<p><b>Create Deal$</b></p>

</body>
        <tr>
            <td valign="top">
                <strong>CATEGORY</strong>
            </td>
            <td valign="top">
                <select name="field-7eb7708749307ba" id="field-7eb7708749307ba">
                    <option value="Housing">Housing</option>
                    <option value="Electronics">Electronics</option>
                    <option value="Books">Books</option>
                    <option value="Others">Others</option>
                </select>
                
            </td>
        </tr>
        <tr>
            <td valign="top">
                <strong>Name:</strong>
            </td>
            <td valign="top">
                <input type="text" name="field-b2cc28dd2f3045a" id="field-b2cc28dd2f3045a" size="40" value="" />
                
            </td>
        </tr>
        <tr>
            <td valign="top">
                <strong>Description:</strong>
            </td>
            <td valign="top">
                <textarea name="field-c95c29be0081228" id="field-c95c29be0081228" rows="6" cols="40"></textarea>
                
            </td>
        </tr>

        <tr>
            <td valign="top">
                <strong>Price:</strong>
            </td>
            <td valign="top">
                <input type="text" name="field-f5d0a66a7aee7c1" id="field-f5d0a66a7aee7c1" size="40" value="" />
                
            </td>
        </tr>
        <tr>
            <td valign="top">
                <strong>Contact Name:</strong>
            </td>
            <td valign="top">
                <input type="text" name="field-936cce7de8657f1" id="field-936cce7de8657f1" size="40" value="" />
                
            </td>
        </tr>
        <tr>
            <td valign="top">
                <strong>Contact Email:</strong>
            </td>
            <td valign="top">
                <input type="text" name="field-f08c8cbbcc8de8d" id="field-f08c8cbbcc8de8d" size="40" value="" />
                
            </td>
        </tr>
        <tr>
			<td valign="top">
				<strong>Contact Phone Number:</strong>
			</td>
			<td valign="top">
				<input type="text" name="field-758b4aae2ac1223" id="field-758b4aae2ac1223" size="40" value="" />
				
			</td>
		</tr>

<tr>

</tr>
<td>
<form action="FileUpload.php" method="post" enctype="multipart/form-data">
    <label for="upload">Image:</label>
    <input type="file" name="upload" id="upload">
    <input type="submit" name="submit" value="Upload">
</form>
</td>
        <tr>
            <td colspan="2" align="center">
                <input type="submit" value=" Post Ad " />
            </td>
        </tr>
    </table>

<form action="http://localhost:3000/static_pages/home" method="link">
<p style="text-align: left;"><input type="submit" value="BACK TO HOME" />&nbsp;</p>
</form>
<!-- End Create Deal$ Form -->
</html>

app/views/static_pages/ddeals.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Budeals</title>
	<link href="/assets/application.css?body=1" media="all" rel="stylesheet" type="text/css" />
	<link href="/assets/ddeals.css?body=1" media="all" rel="stylesheet" type="text/css" />
	<link href="/assets/static_pages.css?body=1" media="all" rel="stylesheet" type="text/css" />
	<link href="/assets/students.css?body=1" media="all" rel="stylesheet" type="text/css" /><script src="/assets/jquery.js?body=1" type="text/javascript"></script><script src="/assets/jquery_ujs.js?body=1" type="text/javascript"></script><script src="/assets/static_pages.js?body=1" type="text/javascript"></script><script src="/assets/students.js?body=1" type="text/javascript"></script><script src="/assets/application.js?body=1" type="text/javascript"></script>
	<meta content="authenticity_token" name="csrf-param" />
	<meta content="6TP0fHI+IY7Fj5NPMMqsxIBQ9tUGa3Ja5taeU28RRi8=" name="csrf-token" />
</head>
<body bgcolor="339966">
</body>
</html>
<p><br />
<title></title>
</p>

<p><span style="font-size:14px;"><span style="font-size:26px;">DISPLAY DEALS</span></span></p>

<form action="">
<input type="checkbox" name="deals" value="housing">Housing<br>
<input type="checkbox" name="deals" value="electronics">Electronics<br>
<input type="checkbox" name="deals" value="books">Books<br>
<input type="checkbox" name="deals" value="others">Others</form>
</br></br>
<input type="submit" value="VIEW">
</br></br>
<form action="http://localhost:3000/static_pages/home" method="link">
<p style="text-align: left;"><input type="submit" value="BACK TO HOME" />&nbsp;</p>
</form>

app/views/static_pages/faq.html.erb
<!DOCTYPE html>
<html>
<head>
<title>FAQ</title>

</head>

<!--<body style="background: url('file:///C:/Users/Raaja/Desktop/budeals1.png')" height="42" width="42"> -->
<body bgcolor=#339966>
<h1><center>FAQ</center></h1>
<p> <font size="5">List of (Questions, Answers) pairs </font></p>
<ol type="1">
  <li><font size="4">What email id should be used to register?</font></li>
     <ul>
      <li><font size="4">Binghamton Email ID only can be used.</font></li>
     </ul>
  <li><font size="4">What is the mode of payment?</font></li>
     <ul>
      <li><font size="4">The buyer should directly contact the seller. There wont be any third party involvement.Each products have the details of the seller.</font></li>
     </ul>
</ol>

<form action="http://localhost:3000/static_pages/home" method="link">
<p style="text-align: left;"><input type="submit" value="BACK TO HOME" />&nbsp;</p>
</form>

</body>
</html>

app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<!doctype html>
<html>
<head>
	<title>HTML Editor - Full Version</title>
</head>
<body bgcolor="339966">
<p style="text-align: center;"><span style="font-size:72px;">BU DEAL$</span></p>

<p style="text-align: center;"><span style="font-size:72px;"><span style="font-size:24px;">Want to sell/buy stuff among BU folks?</span></span></p>

<p style="text-align: center;"><span style="font-size:72px;"><span style="font-size:24px;">You are at the right place!!</span></span></p>

<form action="http://localhost:3000/students/new" method="link">
<p style="text-align: center;"><input height="500" type="submit" value="REGISTER" width="500" />&nbsp;</p>
</form>

<form action="http://localhost:3000/static_pages/login" method="link">
<p style="text-align: center;"><input height="500" type="submit" value="LOGIN" width="500" />&nbsp;</p>
</form>

<form action="http://localhost:3000/static_pages/faq" method="link">
<p style="text-align: center;"><input type="submit" value="FAQ"/>&nbsp;</p>
</form>

</form>
</body>
</html>


app/views/static_pages/index.html.erb
<body bgcolor="339966">
<h1>BUDeal$ MENU</h1>

<form action="http://localhost:3000/deals" method="link">
<input height="500" type="submit" value="DISPLAY DEALS" width="500" />&nbsp;</p>
</form>

<form action="http://localhost:3000/deals/new" method="link">
<input height="500" type="submit" value="CREATE DEALS" width="500" />&nbsp;</p>
</form>

</form>

app/views/static_pages/login.html.erb
<body bgcolor="339966">
<h1>BUDeal$ Login</h1>

<section class="loginform cf">

    <ul>
        <li><label for="usermail">Email</label>
        <input type="email" name="usermail" placeholder="yourname@email.com" required></li>
        <li><label for="password">Password</label>
        <input type="password" name="password" placeholder="password" required></li>

	<form action="http://localhost:3000/static_pages/index" method="link">
	<input type="submit" value="Login" />&nbsp;</p>
	</form>

    </ul>
</form>
</section>

app/views/static_pages/remove_ad.html.erb
<!DOCTYPE html>
<html>
<body bgcolor="339966">

<h style="text-align:center; display:block; font-size:300%;font-family:calligraphy;color:blue;" > Remove your ADS </h>

<p align="center" style="top: 75%; color:red; font-size:150%;font-family:calligraphy;" >You haven't posted any deals yet </p>

<form action="http://localhost:3000/static_pages/home" method="link">
<p style="text-align: left;"><input type="submit" value="BACK TO HOME" />&nbsp;</p>
</form>
</body>
</html>

app/views/students/display.html.erb
<body bgcolor="339966">
<h1>BUDeal$</h1>
<table>
<tr>
<th>FirstName</th>
<th>LastName</th>
<th>EmailId</th>
<th>PhoneNumber</th>
<th></th>
<th></th>
</tr>
<% @students.each do |s| %>
<tr>
<td><%= s.firstname %></td>
<td><%= s.lastname %></td>
<td><%= s.emailid %></td>
<td><%= s.phoneno %></td>
</tr>
<% end %>
</table>

app/views/students/login.html.erb
you are registered.

app/views/students/new.html.erb
<body bgcolor="339966">
<hr>
<%= form_for @student do |f| -%>
    First name: <%= f.text_field :firstname %><br />
    Last name : <%= f.text_field :lastname %><br />
    emailid: <%= f.text_field :emailid %><br />
    password: <%= f.text_field :password %><br />
    phoneno : <%= f.text_field :phoneno %><br />

    <%= f.submit %>
<% end -%>


</form>